---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: authgateway-deployment
  namespace: default
  labels:
    app: authgateway-deployment
spec:
  selector:
    matchLabels:
      app: authgateway-deployment
  template:
    metadata:
      labels:
        app: authgateway-deployment
    spec:
      containers:
        - name: authgateway-service
          image: asia-southeast2-docker.pkg.dev/multiwarehouse-447401/com-multiwarehouse-app-repository/authgateway.service:1.0-SNAPSHOT
          env:
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:postgresql://postgres-service:5432/multiwarehouse?currentSchema=auth&binaryTransfer=true&reWriteBatchedInserts=true&stringtype=unspecified"
            - name: SPRING_DATASOURCE_INITIALIZATION-MODE
              value: "never"
            - name: KAFKA-CONFIG_BOOTSTRAP-SERVERS
              value: "gke-confluent-kafka-cp-kafka-headless:9092"
            - name: KAFKA-CONFIG_SCHEMA-REGISTRY-URL
              value: "http://gke-confluent-kafka-cp-schema-registry:8081"

            - name: SPRING_CLOUD_GATEWAY_ROUTES[0]_URI
              value: "http://user-service:8182"
            - name: SPRING_CLOUD_GATEWAY_ROUTES[1]_URI
              value: "http://user-service:8182"
            - name: SPRING_CLOUD_GATEWAY_ROUTES[2]_URI
              value: "http://warehouse-service:8181"
            - name: SPRING_CLOUD_GATEWAY_ROUTES[3]_URI
              value: "http://warehouse-service:8181"
            - name: SPRING_CLOUD_GATEWAY_ROUTES[4]_URI
              value: "http://user-service:8182"
            - name: SPRING_CLOUD_GATEWAY_ROUTES[5]_URI
              value: "http://user-service:8182"
            - name: SPRING_CLOUD_GATEWAY_ROUTES[6]_URI
              value: "http://product-service:8184"
            - name: SPRING_CLOUD_GATEWAY_ROUTES[7]_URI
              value: "http://product-service:8184"
            - name: SPRING_CLOUD_GATEWAY_ROUTES[8]_URI
              value: "http://inventory-service:8188"
            - name: SPRING_CLOUD_GATEWAY_ROUTES[9]_URI
              value: "http://inventory-service:8188"

          resources:
            limits:
              cpu: "500m"
              memory: "1024Mi"
            requests:
              cpu: "200m"
              memory: "256Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: authgateway-service
  namespace: default
  labels:
    app: authgateway-service
spec:
  selector:
    app: authgateway-deployment
  ports:
    - name: authgateway-service-port
      protocol: TCP
      port: 8190
  type: LoadBalancer
  loadBalancerIP: ""

