services:
  postgresql:
    image: postgres:16
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=mutliwarehouse
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    volumes:
      - './volumes/postgresql_data:/var/lib/postgresql/data'
    networks:
      - ${GLOBAL_NETWORK:-postgres}