server:
  port: 8182

logging:
  level:
    com.multiwarehouse.app: DEBUG

user-service:
  user-change-topic-name: user-change
  warehouse-change-topic-name: warehouse-change

spring:
  application:
    name: multiwarehouse
  datasource:
    url: jdbc:postgresql://localhost:5432/multiwarehouse?currentSchema=user&binaryTransfer=true&reWriteBatchedInserts=true&stringtype=unspecified
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    open-in-view: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    generate-ddl: false
    hibernate:
      ddl-auto: none
  sql:
    init:
      platform: postgres
      mode: always
      schema-locations: classpath:init-schema.sql

kafka-config:
  bootstrap-servers: localhost:19092,localhost:29092,localhost:39092
  schema-registry-url-key: schema.registry.url
  schema-registry-url: http://localhost:8081
  num-of-partitions: 3
  replication-factor: 3

kafka-producer-config:
  key-serializer-class: org.apache.kafka.common.serialization.StringSerializer
  value-serializer-class: io.confluent.kafka.serializers.KafkaAvroSerializer
  compression-type: snappy
  acks: all
  batch-size: 16384
  batch-size-boost-factor: 100
  linger-ms: 5
  request-timeout-ms: 60000
  retry-count: 5

kafka-consumer-config:
  key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
  value-deserializer: io.confluent.kafka.serializers.KafkaAvroDeserializer
  warehouse-change-consumer-group-id: user-warehouse-change-consumer
  auto-offset-reset: earliest
  specific-avro-reader-key: specific.avro.reader
  specific-avro-reader: true
  batch-listener: true
  auto-startup: true
  concurrency-level: 3
  session-timeout-ms: 10000
  heartbeat-interval-ms: 3000
  max-poll-interval-ms: 300000
  max-poll-records: 500
  max-partition-fetch-bytes-default: 1048576
  max-partition-fetch-bytes-boost-factor: 1
  poll-timeout-ms: 150

security:
  jwt:
    text: sulistyo ponco nugroho
    key: pranadipa adamasya satyanugroho
    secret-key: 54b56cbc136f46447341b80eaf3fe2dfac6b16d6cfbabe969572d58dcbd9aee6
    expiration-time: 3600000