/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.multiwarehouse.app.kafka.inventory.avro.model;
@org.apache.avro.specific.AvroGenerated
public enum ActionType implements org.apache.avro.generic.GenericEnumSymbol<ActionType> {
  DEFAULT, CREATED, UPDATED, SOFT_DELETED, HARD_DELETED  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"ActionType\",\"namespace\":\"com.multiwarehouse.app.kafka.inventory.avro.model\",\"symbols\":[\"DEFAULT\",\"CREATED\",\"UPDATED\",\"SOFT_DELETED\",\"HARD_DELETED\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
}
