/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.multiwarehouse.app.kafka.inventory.avro.model;

import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class ProductStockChangeAvroModel extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 3588102864780667726L;


  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"ProductStockChangeAvroModel\",\"namespace\":\"com.multiwarehouse.app.kafka.inventory.avro.model\",\"fields\":[{\"name\":\"ProductStockId\",\"type\":{\"type\":\"string\",\"logicalType\":\"uuid\"}},{\"name\":\"productId\",\"type\":{\"type\":\"string\",\"logicalType\":\"uuid\"}},{\"name\":\"quantity\",\"type\":\"int\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static final SpecificData MODEL$ = new SpecificData();
  static {
    MODEL$.addLogicalTypeConversion(new org.apache.avro.Conversions.UUIDConversion());
  }

  private static final BinaryMessageEncoder<ProductStockChangeAvroModel> ENCODER =
      new BinaryMessageEncoder<>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<ProductStockChangeAvroModel> DECODER =
      new BinaryMessageDecoder<>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<ProductStockChangeAvroModel> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<ProductStockChangeAvroModel> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<ProductStockChangeAvroModel> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this ProductStockChangeAvroModel to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a ProductStockChangeAvroModel from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a ProductStockChangeAvroModel instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static ProductStockChangeAvroModel fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  private java.util.UUID ProductStockId;
  private java.util.UUID productId;
  private int quantity;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public ProductStockChangeAvroModel() {}

  /**
   * All-args constructor.
   * @param ProductStockId The new value for ProductStockId
   * @param productId The new value for productId
   * @param quantity The new value for quantity
   */
  public ProductStockChangeAvroModel(java.util.UUID ProductStockId, java.util.UUID productId, java.lang.Integer quantity) {
    this.ProductStockId = ProductStockId;
    this.productId = productId;
    this.quantity = quantity;
  }

  @Override
  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }

  // Used by DatumWriter.  Applications should not call.
  @Override
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return ProductStockId;
    case 1: return productId;
    case 2: return quantity;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  private static final org.apache.avro.Conversion<?>[] conversions =
      new org.apache.avro.Conversion<?>[] {
      new org.apache.avro.Conversions.UUIDConversion(),
      new org.apache.avro.Conversions.UUIDConversion(),
      null,
      null
  };

  @Override
  public org.apache.avro.Conversion<?> getConversion(int field) {
    return conversions[field];
  }

  // Used by DatumReader.  Applications should not call.
  @Override
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: ProductStockId = (java.util.UUID)value$; break;
    case 1: productId = (java.util.UUID)value$; break;
    case 2: quantity = (java.lang.Integer)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'ProductStockId' field.
   * @return The value of the 'ProductStockId' field.
   */
  public java.util.UUID getProductStockId() {
    return ProductStockId;
  }


  /**
   * Sets the value of the 'ProductStockId' field.
   * @param value the value to set.
   */
  public void setProductStockId(java.util.UUID value) {
    this.ProductStockId = value;
  }

  /**
   * Gets the value of the 'productId' field.
   * @return The value of the 'productId' field.
   */
  public java.util.UUID getProductId() {
    return productId;
  }


  /**
   * Sets the value of the 'productId' field.
   * @param value the value to set.
   */
  public void setProductId(java.util.UUID value) {
    this.productId = value;
  }

  /**
   * Gets the value of the 'quantity' field.
   * @return The value of the 'quantity' field.
   */
  public int getQuantity() {
    return quantity;
  }


  /**
   * Sets the value of the 'quantity' field.
   * @param value the value to set.
   */
  public void setQuantity(int value) {
    this.quantity = value;
  }

  /**
   * Creates a new ProductStockChangeAvroModel RecordBuilder.
   * @return A new ProductStockChangeAvroModel RecordBuilder
   */
  public static com.multiwarehouse.app.kafka.inventory.avro.model.ProductStockChangeAvroModel.Builder newBuilder() {
    return new com.multiwarehouse.app.kafka.inventory.avro.model.ProductStockChangeAvroModel.Builder();
  }

  /**
   * Creates a new ProductStockChangeAvroModel RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new ProductStockChangeAvroModel RecordBuilder
   */
  public static com.multiwarehouse.app.kafka.inventory.avro.model.ProductStockChangeAvroModel.Builder newBuilder(com.multiwarehouse.app.kafka.inventory.avro.model.ProductStockChangeAvroModel.Builder other) {
    if (other == null) {
      return new com.multiwarehouse.app.kafka.inventory.avro.model.ProductStockChangeAvroModel.Builder();
    } else {
      return new com.multiwarehouse.app.kafka.inventory.avro.model.ProductStockChangeAvroModel.Builder(other);
    }
  }

  /**
   * Creates a new ProductStockChangeAvroModel RecordBuilder by copying an existing ProductStockChangeAvroModel instance.
   * @param other The existing instance to copy.
   * @return A new ProductStockChangeAvroModel RecordBuilder
   */
  public static com.multiwarehouse.app.kafka.inventory.avro.model.ProductStockChangeAvroModel.Builder newBuilder(com.multiwarehouse.app.kafka.inventory.avro.model.ProductStockChangeAvroModel other) {
    if (other == null) {
      return new com.multiwarehouse.app.kafka.inventory.avro.model.ProductStockChangeAvroModel.Builder();
    } else {
      return new com.multiwarehouse.app.kafka.inventory.avro.model.ProductStockChangeAvroModel.Builder(other);
    }
  }

  /**
   * RecordBuilder for ProductStockChangeAvroModel instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<ProductStockChangeAvroModel>
    implements org.apache.avro.data.RecordBuilder<ProductStockChangeAvroModel> {

    private java.util.UUID ProductStockId;
    private java.util.UUID productId;
    private int quantity;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$, MODEL$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.multiwarehouse.app.kafka.inventory.avro.model.ProductStockChangeAvroModel.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.ProductStockId)) {
        this.ProductStockId = data().deepCopy(fields()[0].schema(), other.ProductStockId);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.productId)) {
        this.productId = data().deepCopy(fields()[1].schema(), other.productId);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.quantity)) {
        this.quantity = data().deepCopy(fields()[2].schema(), other.quantity);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
    }

    /**
     * Creates a Builder by copying an existing ProductStockChangeAvroModel instance
     * @param other The existing instance to copy.
     */
    private Builder(com.multiwarehouse.app.kafka.inventory.avro.model.ProductStockChangeAvroModel other) {
      super(SCHEMA$, MODEL$);
      if (isValidValue(fields()[0], other.ProductStockId)) {
        this.ProductStockId = data().deepCopy(fields()[0].schema(), other.ProductStockId);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.productId)) {
        this.productId = data().deepCopy(fields()[1].schema(), other.productId);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.quantity)) {
        this.quantity = data().deepCopy(fields()[2].schema(), other.quantity);
        fieldSetFlags()[2] = true;
      }
    }

    /**
      * Gets the value of the 'ProductStockId' field.
      * @return The value.
      */
    public java.util.UUID getProductStockId() {
      return ProductStockId;
    }


    /**
      * Sets the value of the 'ProductStockId' field.
      * @param value The value of 'ProductStockId'.
      * @return This builder.
      */
    public com.multiwarehouse.app.kafka.inventory.avro.model.ProductStockChangeAvroModel.Builder setProductStockId(java.util.UUID value) {
      validate(fields()[0], value);
      this.ProductStockId = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'ProductStockId' field has been set.
      * @return True if the 'ProductStockId' field has been set, false otherwise.
      */
    public boolean hasProductStockId() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'ProductStockId' field.
      * @return This builder.
      */
    public com.multiwarehouse.app.kafka.inventory.avro.model.ProductStockChangeAvroModel.Builder clearProductStockId() {
      ProductStockId = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'productId' field.
      * @return The value.
      */
    public java.util.UUID getProductId() {
      return productId;
    }


    /**
      * Sets the value of the 'productId' field.
      * @param value The value of 'productId'.
      * @return This builder.
      */
    public com.multiwarehouse.app.kafka.inventory.avro.model.ProductStockChangeAvroModel.Builder setProductId(java.util.UUID value) {
      validate(fields()[1], value);
      this.productId = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'productId' field has been set.
      * @return True if the 'productId' field has been set, false otherwise.
      */
    public boolean hasProductId() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'productId' field.
      * @return This builder.
      */
    public com.multiwarehouse.app.kafka.inventory.avro.model.ProductStockChangeAvroModel.Builder clearProductId() {
      productId = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'quantity' field.
      * @return The value.
      */
    public int getQuantity() {
      return quantity;
    }


    /**
      * Sets the value of the 'quantity' field.
      * @param value The value of 'quantity'.
      * @return This builder.
      */
    public com.multiwarehouse.app.kafka.inventory.avro.model.ProductStockChangeAvroModel.Builder setQuantity(int value) {
      validate(fields()[2], value);
      this.quantity = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'quantity' field has been set.
      * @return True if the 'quantity' field has been set, false otherwise.
      */
    public boolean hasQuantity() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'quantity' field.
      * @return This builder.
      */
    public com.multiwarehouse.app.kafka.inventory.avro.model.ProductStockChangeAvroModel.Builder clearQuantity() {
      fieldSetFlags()[2] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public ProductStockChangeAvroModel build() {
      try {
        ProductStockChangeAvroModel record = new ProductStockChangeAvroModel();
        record.ProductStockId = fieldSetFlags()[0] ? this.ProductStockId : (java.util.UUID) defaultValue(fields()[0]);
        record.productId = fieldSetFlags()[1] ? this.productId : (java.util.UUID) defaultValue(fields()[1]);
        record.quantity = fieldSetFlags()[2] ? this.quantity : (java.lang.Integer) defaultValue(fields()[2]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<ProductStockChangeAvroModel>
    WRITER$ = (org.apache.avro.io.DatumWriter<ProductStockChangeAvroModel>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<ProductStockChangeAvroModel>
    READER$ = (org.apache.avro.io.DatumReader<ProductStockChangeAvroModel>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}










