---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: warehouse-deployment
  namespace: default
  labels:
    app: warehouse-deployment
spec:
  selector:
    matchLabels:
      app: warehouse-deployment
  template:
    metadata:
      labels:
        app: warehouse-deployment
    spec:
      containers:
        - name: warehouse-service
          image: com.multiwarehouse.app/warehouse.service:1.0-SNAPSHOT
          env:
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:postgresql://host.docker.internal:5432/multiwarehouse?currentSchema=warehouse&binaryTransfer=true&reWriteBatchedInserts=true&stringtype=unspecified"
            - name: KAFKA-CONFIG_BOOTSTRAP-SERVERS
              value: "local-confluent-kafka-cp-kafka-headless:9092"
            - name: KAFKA-CONFIG_SCHEMA-REGISTRY-URL
              value: "http://local-confluent-kafka-cp-schema-registry:8081"
          resources:
            limits:
              cpu: "500m"
              memory: "1024Mi"
            requests:
              cpu: "200m"
              memory: "256Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: warehouse-service
  namespace: default
  labels:
    app: warehouse-service
spec:
  selector:
    app: warehouse-deployment
  ports:
    - name: warehouse-service-port
      protocol: TCP
      port: 8181
  type: LoadBalancer
  loadBalancerIP: ""

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-deployment
  namespace: default
  labels:
    app: user-deployment
spec:
  selector:
    matchLabels:
      app: user-deployment
  template:
    metadata:
      labels:
        app: user-deployment
    spec:
      containers:
        - name: user-service
          image: com.multiwarehouse.app/user.service:1.0-SNAPSHOT
          env:
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:postgresql://host.docker.internal:5432/multiwarehouse?currentSchema=user&binaryTransfer=true&reWriteBatchedInserts=true&stringtype=unspecified"
            - name: KAFKA-CONFIG_BOOTSTRAP-SERVERS
              value: "local-confluent-kafka-cp-kafka-headless:9092"
            - name: KAFKA-CONFIG_SCHEMA-REGISTRY-URL
              value: "http://local-confluent-kafka-cp-schema-registry:8081"
          resources:
            limits:
              cpu: "500m"
              memory: "1024Mi"
            requests:
              cpu: "200m"
              memory: "256Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: user-service
  namespace: default
  labels:
    app: user-service
spec:
  selector:
    app: user-deployment
  ports:
    - name: user-service-port
      protocol: TCP
      port: 8182
  type: LoadBalancer
  loadBalancerIP: ""

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-deployment
  namespace: default
  labels:
    app: product-deployment
spec:
  selector:
    matchLabels:
      app: product-deployment
  template:
    metadata:
      labels:
        app: product-deployment
    spec:
      containers:
        - name: product-service
          image: com.multiwarehouse.app/product.service:1.0-SNAPSHOT
          env:
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:postgresql://host.docker.internal:5432/multiwarehouse?currentSchema=product&binaryTransfer=true&reWriteBatchedInserts=true&stringtype=unspecified"
            - name: KAFKA-CONFIG_BOOTSTRAP-SERVERS
              value: "local-confluent-kafka-cp-kafka-headless:9092"
            - name: KAFKA-CONFIG_SCHEMA-REGISTRY-URL
              value: "http://local-confluent-kafka-cp-schema-registry:8081"
          resources:
            limits:
              cpu: "500m"
              memory: "1024Mi"
            requests:
              cpu: "200m"
              memory: "256Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: product-service
  namespace: default
  labels:
    app: product-service
spec:
  selector:
    app: product-deployment
  ports:
    - name: product-service-port
      protocol: TCP
      port: 8184
  type: LoadBalancer
  loadBalancerIP: ""

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: inventory-deployment
  namespace: default
  labels:
    app: inventory-deployment
spec:
  selector:
    matchLabels:
      app: inventory-deployment
  template:
    metadata:
      labels:
        app: inventory-deployment
    spec:
      containers:
        - name: inventory-service
          image: com.multiwarehouse.app/inventory.service:1.0-SNAPSHOT
          env:
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:postgresql://host.docker.internal:5432/multiwarehouse?currentSchema=inventory&binaryTransfer=true&reWriteBatchedInserts=true&stringtype=unspecified"
            - name: KAFKA-CONFIG_BOOTSTRAP-SERVERS
              value: "local-confluent-kafka-cp-kafka-headless:9092"
            - name: KAFKA-CONFIG_SCHEMA-REGISTRY-URL
              value: "http://local-confluent-kafka-cp-schema-registry:8081"
          resources:
            limits:
              cpu: "500m"
              memory: "1024Mi"
            requests:
              cpu: "200m"
              memory: "256Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: inventory-service
  namespace: default
  labels:
    app: inventory-service
spec:
  selector:
    app: inventory-deployment
  ports:
    - name: inventory-service-port
      protocol: TCP
      port: 8188
  type: LoadBalancer
  loadBalancerIP: ""
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: inventory-hpa
  namespace: default
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: inventory-deployment
  minReplicas: 2
  maxReplicas: 4
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: authgateway-deployment
  namespace: default
  labels:
    app: authgateway-deployment
spec:
  selector:
    matchLabels:
      app: authgateway-deployment
  template:
    metadata:
      labels:
        app: authgateway-deployment
    spec:
      containers:
        - name: authgateway-service
          image: com.multiwarehouse.app/authgateway.service:1.0-SNAPSHOT
          env:
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:postgresql://host.docker.internal:5432/multiwarehouse?currentSchema=auth&binaryTransfer=true&reWriteBatchedInserts=true&stringtype=unspecified"
            - name: KAFKA-CONFIG_BOOTSTRAP-SERVERS
              value: "local-confluent-kafka-cp-kafka-headless:9092"
            - name: KAFKA-CONFIG_SCHEMA-REGISTRY-URL
              value: "http://local-confluent-kafka-cp-schema-registry:8081"

            - name: SPRING_CLOUD_GATEWAY_ROUTES_0_ID
              value: "user-service"
            - name: SPRING_CLOUD_GATEWAY_ROUTES_0_URI
              value: "http://user-service:8182"
            - name: SPRING_CLOUD_GATEWAY_ROUTES_0_PREDICATES_0
              value: "Path=/auth/**"
            - name: SPRING_CLOUD_GATEWAY_ROUTES_1_ID
              value: "user-service"
            - name: SPRING_CLOUD_GATEWAY_ROUTES_1_URI
              value: "http://user-service:8182"
            - name: SPRING_CLOUD_GATEWAY_ROUTES_1_PREDICATES_0
              value: "Path=/me"
            - name: SPRING_CLOUD_GATEWAY_ROUTES_1_PREDICATES_1
              value: "Method= GET, PUT"
            - name: SPRING_CLOUD_GATEWAY_ROUTES_2_ID
              value: "warehouse-service"
            - name: SPRING_CLOUD_GATEWAY_ROUTES_2_URI
              value: "http://warehouse-service:8181"
            - name: SPRING_CLOUD_GATEWAY_ROUTES_2_PREDICATES_0
              value: "Path=/warehouses/**"
            - name: SPRING_CLOUD_GATEWAY_ROUTES_2_PREDICATES_1
              value: "Method= GET"
            - name: SPRING_CLOUD_GATEWAY_ROUTES_3_ID
              value: "warehouse-service"
            - name: SPRING_CLOUD_GATEWAY_ROUTES_3_URI
              value: "http://warehouse-service:8181"
            - name: SPRING_CLOUD_GATEWAY_ROUTES_3_PREDICATES_0
              value: "Path=/warehouses/**"
            - name: SPRING_CLOUD_GATEWAY_ROUTES_3_PREDICATES_1
              value: "Method= POST, PUT, DELETE"
            - name: SPRING_CLOUD_GATEWAY_ROUTES_4_ID
              value: "user-service"
            - name: SPRING_CLOUD_GATEWAY_ROUTES_4_URI
              value: "http://user-service:8182"
            - name: SPRING_CLOUD_GATEWAY_ROUTES_4_PREDICATES_0
              value: "Path=/users/**"
            - name: SPRING_CLOUD_GATEWAY_ROUTES_4_PREDICATES_1
              value: "Method= GET, PUT"
            - name: SPRING_CLOUD_GATEWAY_ROUTES_5_ID
              value: "user-service"
            - name: SPRING_CLOUD_GATEWAY_ROUTES_5_URI
              value: "http://user-service:8182"
            - name: SPRING_CLOUD_GATEWAY_ROUTES_5_PREDICATES_0
              value: "Path=/users/**"
            - name: SPRING_CLOUD_GATEWAY_ROUTES_5_PREDICATES_1
              value: "Method= POST, DELETE"
            - name: SPRING_CLOUD_GATEWAY_ROUTES_6_ID
              value: "product-service"
            - name: SPRING_CLOUD_GATEWAY_ROUTES_6_URI
              value: "http://product-service:8184"
            - name: SPRING_CLOUD_GATEWAY_ROUTES_6_PREDICATES_0
              value: "Path=/product_categories/**, /products/**"
            - name: SPRING_CLOUD_GATEWAY_ROUTES_6_PREDICATES_1
              value: "Method= GET"
            - name: SPRING_CLOUD_GATEWAY_ROUTES_7_ID
              value: "product-service"
            - name: SPRING_CLOUD_GATEWAY_ROUTES_7_URI
              value: "http://product-service:8184"
            - name: SPRING_CLOUD_GATEWAY_ROUTES_7_PREDICATES_0
              value: "Path=/product_categories/**, /products/**"
            - name: SPRING_CLOUD_GATEWAY_ROUTES_7_PREDICATES_1
              value: "Method= POST, PUT, DELETE"
            - name: SPRING_CLOUD_GATEWAY_ROUTES_8_ID
              value: "inventory-service"
            - name: SPRING_CLOUD_GATEWAY_ROUTES_8_URI
              value: "http://inventory-service:8188"
            - name: SPRING_CLOUD_GATEWAY_ROUTES_8_PREDICATES_0
              value: "Path=/inventories/by_warehouse/**, /stock_mutations/by_warehouse/**"
            - name: SPRING_CLOUD_GATEWAY_ROUTES_8_PREDICATES_1
              value: "Method= GET, POST"
            - name: SPRING_CLOUD_GATEWAY_ROUTES_9_ID
              value: "inventory-service"
            - name: SPRING_CLOUD_GATEWAY_ROUTES_9_URI
              value: "http://inventory-service:8188"
            - name: SPRING_CLOUD_GATEWAY_ROUTES_9_PREDICATES_0
              value: "Path=/stock_mutations/**"
            - name: SPRING_CLOUD_GATEWAY_ROUTES_9_PREDICATES_1
              value: "Method= PUT"

          resources:
            limits:
              cpu: "500m"
              memory: "1024Mi"
            requests:
              cpu: "200m"
              memory: "256Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: authgateway-service
  namespace: default
  labels:
    app: authgateway-service
spec:
  selector:
    app: authgateway-deployment
  ports:
    - name: authgateway-service-port
      protocol: TCP
      port: 8190
  type: LoadBalancer
  loadBalancerIP: ""
